Update README.md
PicasoTheDeal/Guess-The-Number-Game pull request #1
Opened 2024-08-14 18:29 UTC by KirubelYonas

2024-08-15 18:27 UTC, AXER-doc requested changes
One line of the code is NOT supported in C++11.
```
$ g++ -std=c++11 -pedantic -Werror -Wall 'The Game/main.cpp'
The Game/main.cpp:77:14: error: structured bindings only available with ‘-std=c++17’ or ‘-std=gnu++17’ [-Werror=c++17-extensions]
   77 |         auto [corNum, corPos] = checkGuess(randomNumber, userGuess);
      |              ^
```

2024-08-15 19:19 UTC, KirubelYonas commented
You are right about that. what about we include other languages such as PHP, JavaScript, and C#.

2024-08-15 19:20 UTC, KirubelYonas reviewed
Approved

2024-08-15 19:25 UTC, KirubelYonas reviewed
I think we should add this as kata on code wars

2024-08-15 20:53 UTC, KirubelYonas commented on README.md
> +# Number Guessing Game in C++
should we add this to leetcode

2024-08-16 13:47 UTC, KirubelYonas commented
> One line of the code is NOT supported in C++11.
> 
> ```
> $ g++ -std=c++11 -pedantic -Werror -Wall 'The Game/main.cpp'
> The Game/main.cpp:77:14: error: structured bindings only available with ‘-std=c++17’ or ‘-std=gnu++17’ [-Werror=c++17-extensions]
>    77 |         auto [corNum, corPos] = checkGuess(randomNumber, userGuess);
>       |              ^
> ```

I debugged and it worked fine

2024-08-17 07:35 UTC, closed without merging